name: "Bug Report"
description: Report an issue with Routes.
title: "[ISSUE] - "
labels: 'Bug'
body:
- type: markdown
  attributes:
    value: |
      Please [search for existing issues](https://github.com/Nevcairiel/Routes/issues) before creating a new one.

- type: textarea
  attributes:
    label: Description
    description: What did you expect to happen, and what happened instead?
  validations:
    required: true

- type: input
  attributes:
    label: Routes Version
    description: |
      You can see the current version of Routes by checking the CurseForge desktop app.
    placeholder: "v1.0.0"
  validations:
    required: true

- type: dropdown
  id: flavor
  attributes:
    label: World of Warcraft Version
    description: What version of World of Warcraft are are you running?
    options:
      - Retail (Default)
      - Classic Vanilla
      - Classic Wrath of the Lich King
  validations:
    required: true

- type: checkboxes
  id: testing
  attributes:
    label: Testing Isolation
    description: Did you try having Routes as the only enabled addon and everything else disabled?
    options:
      - label: "No"
      - label: "Yes, without any related optional dependencies."
      - label: "Yes, with related optional dependencies."
  validations:
    required: true

- type: textarea
  attributes:
    label: Lua Error(s)
    description: |
      Do you have any error(s)? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://www.curseforge.com/wow/addons/bugsack) & [BugGrabber](https://www.curseforge.com/wow/addons/bug-grabber). Both addons are needed.
    render: true
  validations:
    required: false

- type: textarea
  attributes:
    label: Reproduction Steps
    description: Please list out the steps to reproduce your issue. Please verify that your reproduction steps are enough to reproduce the problem.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true

- type: input
  attributes:
    label: Last Known Good Version
    description: |
      Was Routes working in a previous version before your issue? If so, what was your last known good version?
    placeholder: "v1.0.0"
  validations:
    required: false

- type: textarea
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your problem.
    placeholder: Attach directly here with copy & paste, DO NOT link to other sites.
  validations:
    required: false

- type: textarea
  attributes:
    label: Additional Information
    description: |
      If you have any additional information, please post that here.
    render: true
  validations:
    required: false
