name: "Feature request"
description: Suggest a feature for Routes.
title: "[FEATURE] - "
labels: 'Feature'

body:
- type: markdown
  attributes:
    value: |
      Please [search for existing issues](https://github.com/Nevcairiel/Routes/issues) before creating a new one.

- type: textarea
  attributes:
    label: Description
    description: Describe the issues and/or needs of your feature request.
  validations:
    required: true

- type: textarea
  attributes:
    label: Solutions
    description: |
      Describe the possible solutions that you would like to see implemented.
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional Information
    description: |
      If you have any additional information, please post that here.
    render: true
  validations:
    required: false
