-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/routes/localization/

local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Routes", "esES") or AceLocale:NewLocale("Routes", "esMX")
if not L then return end

--@localization(locale="esES", format="lua_additive_table", table-name="L", handle-unlocalized="comment")@
